#!/usr/bin/env python3
"""Generate inference/src/tokenizer/nfc_table.zig from a pinned Unicode Character Database.

The table is canonical composition data for NFC (UAX #15): nonzero canonical
combining classes, full canonical decompositions, and primary composites
(two-character decompositions not in Full_Composition_Exclusion). Hangul is
algorithmic and not tabled. The table is committed; this script only
regenerates it. Downloads are cached under .zig-cache/ucd/<version>/ and
checked against pinned digests; NormalizationTest.txt is fetched too, for the
conformance test in nfc.zig, which runs whenever that file is cached.

    python3 scripts/tokenizer-nfc.py
"""
import argparse
import hashlib
import urllib.request
from pathlib import Path

VERSION = '17.0.0'
BASE = f'https://www.unicode.org/Public/{VERSION}/ucd'
ROOT = Path(__file__).resolve().parents[1]

# name -> sha256, pinned for the version above.
SOURCES = {
    'UnicodeData.txt': '2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c',
    'DerivedNormalizationProps.txt': '71fd6a206a2c0cdd41feb6b7f656aa31091db45e9cedc926985d718397f9e488',
    'NormalizationTest.txt': '5019ffd530751a741900c849c0e010332f142a3612234639bd200b82138a87db',
}

parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument('--ucd-dir', type=Path, default=ROOT / '.zig-cache/ucd' / VERSION,
                    help='where the UCD files are cached/downloaded')
parser.add_argument('--output', type=Path, default=ROOT / 'inference/src/tokenizer/nfc_table.zig')
parser.add_argument('--offline', action='store_true', help='fail instead of downloading')
args = parser.parse_args()


def source(name):
    path = args.ucd_dir / name
    if not path.exists():
        if args.offline:
            parser.error(f'missing {path}; run without --offline')
        args.ucd_dir.mkdir(parents=True, exist_ok=True)
        url = f'{BASE}/{name}'
        print('fetch', url)
        with urllib.request.urlopen(url, timeout=60) as response:
            path.write_bytes(response.read())
    data = path.read_bytes()
    digest = hashlib.sha256(data).hexdigest()
    if digest != SOURCES[name]:
        parser.error(f'{path}: sha256 {digest} differs from the pinned {SOURCES[name]}')
    return data.decode()


def expand_ranges(text):
    """UnicodeData.txt rows, with <..., First>/<..., Last> pairs expanded."""
    rows = {}
    first = None
    for line in text.splitlines():
        f = line.split(';')
        cp = int(f[0], 16)
        if f[1].endswith(', First>'):
            first = cp
            continue
        if f[1].endswith(', Last>'):
            for c in range(first, cp + 1):
                rows[c] = f
            continue
        rows[cp] = f
    return rows


rows = expand_ranges(source('UnicodeData.txt'))
exclusions = set()
for line in source('DerivedNormalizationProps.txt').splitlines():
    line = line.split('#', 1)[0].strip()
    if not line:
        continue
    fields = [x.strip() for x in line.split(';')]
    if fields[1] != 'Full_Composition_Exclusion':
        continue
    lo, _, hi = fields[0].partition('..')
    exclusions.update(range(int(lo, 16), int(hi or lo, 16) + 1))
source('NormalizationTest.txt')

classes = {cp: int(f[3]) for cp, f in rows.items() if int(f[3])}
canonical = {}
for cp, f in rows.items():
    d = f[5]
    if d and not d.startswith('<'):
        canonical[cp] = [int(x, 16) for x in d.split()]


def full(cp):
    return [y for x in canonical[cp] for y in (full(x) if x in canonical else [x])]


decompositions = {cp: full(cp) for cp in sorted(canonical)}
compositions = sorted(
    (d[0], d[1], cp) for cp, d in canonical.items() if len(d) == 2 and cp not in exclusions)
assert all(0xAC00 > cp or cp > 0xD7A3 for cp in canonical), 'Hangul must stay algorithmic'
assert all(len(d) <= 4 for d in decompositions.values())

ranges = []
for cp in sorted(classes):
    if ranges and ranges[-1][1] == cp - 1 and ranges[-1][2] == classes[cp]:
        ranges[-1][1] = cp
    else:
        ranges.append([cp, cp, classes[cp]])

pool = []
index = []
for cp, d in decompositions.items():
    index.append((cp, len(pool), len(d)))
    pool.extend(d)
assert len(pool) < 1 << 16


def emit(name, doc, kind, items, per_line):
    lines = [f'/// {doc}', f'pub const {name} = [_]{kind}{{']
    for i in range(0, len(items), per_line):
        lines.append('    ' + ' '.join(items[i:i + per_line]))
    lines.append('};')
    return '\n'.join(lines)


out = '\n\n'.join([
    f'//! Generated by scripts/tokenizer-nfc.py from UCD {VERSION}; do not edit.\n'
    '//! Canonical composition data for NFC (see nfc.zig); Unicode data is\n'
    '//! Copyright © Unicode, Inc., under the Unicode License (THIRD_PARTY_NOTICES.md).',
    f'pub const version = "{VERSION}";',
    emit('classes', 'Nonzero canonical combining classes: first, last (inclusive), class.',
         '[3]u21', [f'.{{ 0x{a:X}, 0x{b:X}, {c} }},' for a, b, c in ranges], 4),
    emit('decompositions', 'Full canonical decompositions but Hangul, by code point: code point, `pool` start, length.',
         '[3]u21', [f'.{{ 0x{a:X}, {b}, {c} }},' for a, b, c in index], 5),
    emit('pool', 'The code points `decompositions` index.', 'u21', [f'0x{c:X},' for c in pool], 12),
    emit('compositions', 'Primary composites by (first, second): first, second, composite.',
         '[3]u21', [f'.{{ 0x{a:X}, 0x{b:X}, 0x{c:X} }},' for a, b, c in compositions], 4),
]) + '\n'
args.output.write_text(out)
print(f'{len(ranges)} class ranges, {len(index)} decompositions ({len(pool)} code points), '
      f'{len(compositions)} compositions -> {args.output} ({len(out)} bytes)')
